[package]
name = "controlmylights"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["ws"] }
axum-macros = "0.5.0"
axum_thiserror = "0.1.0"
futures = "0.3.31"
serde = "1.0.218"
shuttle-axum = "0.52.0"
shuttle-runtime = "0.52.0"
thiserror = "2.0.11"
tokio = "1.28.2"
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing = "0.1.41"
