name: Build 🔨 & Deploy 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: client

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: |
            - cwd: ./client
              args: [--frozen-lockfile]

      - run: pnpm build
        working-directory: ./client

      - uses: actions/upload-artifact@v4
        with:
          name: public
          path: ./client/dist

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: server

      - uses: actions/cache@v4
        with:
          path: |
            ./.cargo/registry
            ./.cargo/git
            ./server/target
          key: ${{ runner.os }}-server-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo build --verbose --release
        working-directory: ./server

      - uses: actions/upload-artifact@v4
        with:
          name: server
          path: ./server/target/release/controlmylights
